/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";
import styles from "../styles/Home.module.css";
import HomePage from "../modules/homePage";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head data-testid="home-heading">
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        {/*<link rel="icon" href="/favicon.ico" />*/}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>

      <HomePage />
    </div>
  );
}
